name: Atualizar cotação ESALQ

on:
  schedule:
    - cron: '0 10 * * 1-5' # seg a sex 10h UTC, 7 horário de Brasília
  workflow_dispatch:      # Permite executar manualmente pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install xlrd==1.2.0 jinja2

      - name: Rodar script de geração
        run: python scripts/gerar_html.py

      - name: Commit e push se houve mudanças
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Atualiza cotação automaticamente" || echo "Sem mudanças"
          git push
