name: Atualizar cotação ESALQ

on:
  schedule:
    - cron: '0 22 * * 1-5' # seg a sex 22 UTC, 19:00h horário de Brasília
  workflow_dispatch:      # Permite executar manualmente pelo GitHub

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libnss3 libatk-bridge2.0-0 libxss1 libasound2t64 libgtk-3-0

      - name: Instalar dependências Python
        run: pip install playwright jinja2

      - name: Instalar browsers do Playwright
        run: playwright install --with-deps

      - name: Rodar script Python
        run: python scripts/gerar_html.py

      - name: Commit e push se houve mudanças
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Atualiza cotação via JS" || echo "Sem mudanças"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
